// Generated by gencpp from file head_posture_module/HeadPosture.msg
// DO NOT EDIT!


#ifndef HEAD_POSTURE_MODULE_MESSAGE_HEADPOSTURE_H
#define HEAD_POSTURE_MODULE_MESSAGE_HEADPOSTURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace head_posture_module
{
template <class ContainerAllocator>
struct HeadPosture_
{
  typedef HeadPosture_<ContainerAllocator> Type;

  HeadPosture_()
    : pose_visible(false)
    , calibrated(false)
    , head_down(false)
    , posture_score(0.0)
    , head_drop_ratio(0.0)
    , baseline_ratio(0.0)
    , consecutive_droop_frames(0)
    , stamp()  {
    }
  HeadPosture_(const ContainerAllocator& _alloc)
    : pose_visible(false)
    , calibrated(false)
    , head_down(false)
    , posture_score(0.0)
    , head_drop_ratio(0.0)
    , baseline_ratio(0.0)
    , consecutive_droop_frames(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _pose_visible_type;
  _pose_visible_type pose_visible;

   typedef uint8_t _calibrated_type;
  _calibrated_type calibrated;

   typedef uint8_t _head_down_type;
  _head_down_type head_down;

   typedef float _posture_score_type;
  _posture_score_type posture_score;

   typedef float _head_drop_ratio_type;
  _head_drop_ratio_type head_drop_ratio;

   typedef float _baseline_ratio_type;
  _baseline_ratio_type baseline_ratio;

   typedef int32_t _consecutive_droop_frames_type;
  _consecutive_droop_frames_type consecutive_droop_frames;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::head_posture_module::HeadPosture_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::head_posture_module::HeadPosture_<ContainerAllocator> const> ConstPtr;

}; // struct HeadPosture_

typedef ::head_posture_module::HeadPosture_<std::allocator<void> > HeadPosture;

typedef boost::shared_ptr< ::head_posture_module::HeadPosture > HeadPosturePtr;
typedef boost::shared_ptr< ::head_posture_module::HeadPosture const> HeadPostureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::head_posture_module::HeadPosture_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::head_posture_module::HeadPosture_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::head_posture_module::HeadPosture_<ContainerAllocator1> & lhs, const ::head_posture_module::HeadPosture_<ContainerAllocator2> & rhs)
{
  return lhs.pose_visible == rhs.pose_visible &&
    lhs.calibrated == rhs.calibrated &&
    lhs.head_down == rhs.head_down &&
    lhs.posture_score == rhs.posture_score &&
    lhs.head_drop_ratio == rhs.head_drop_ratio &&
    lhs.baseline_ratio == rhs.baseline_ratio &&
    lhs.consecutive_droop_frames == rhs.consecutive_droop_frames &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::head_posture_module::HeadPosture_<ContainerAllocator1> & lhs, const ::head_posture_module::HeadPosture_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace head_posture_module

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::head_posture_module::HeadPosture_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_posture_module::HeadPosture_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::head_posture_module::HeadPosture_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::head_posture_module::HeadPosture_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_posture_module::HeadPosture_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_posture_module::HeadPosture_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::head_posture_module::HeadPosture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf8798f74ba00625c0c934cef96b9d09";
  }

  static const char* value(const ::head_posture_module::HeadPosture_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf8798f74ba00625ULL;
  static const uint64_t static_value2 = 0xc0c934cef96b9d09ULL;
};

template<class ContainerAllocator>
struct DataType< ::head_posture_module::HeadPosture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "head_posture_module/HeadPosture";
  }

  static const char* value(const ::head_posture_module::HeadPosture_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::head_posture_module::HeadPosture_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Head posture evidence from the MediaPipe pose node.\n"
"# Input to the fatigue monitor; does not trigger speech by itself.\n"
"\n"
"bool pose_visible\n"
"bool calibrated\n"
"bool head_down\n"
"\n"
"float32 posture_score\n"
"float32 head_drop_ratio\n"
"float32 baseline_ratio\n"
"\n"
"int32 consecutive_droop_frames\n"
"time stamp\n"
;
  }

  static const char* value(const ::head_posture_module::HeadPosture_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::head_posture_module::HeadPosture_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_visible);
      stream.next(m.calibrated);
      stream.next(m.head_down);
      stream.next(m.posture_score);
      stream.next(m.head_drop_ratio);
      stream.next(m.baseline_ratio);
      stream.next(m.consecutive_droop_frames);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeadPosture_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::head_posture_module::HeadPosture_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::head_posture_module::HeadPosture_<ContainerAllocator>& v)
  {
    s << indent << "pose_visible: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pose_visible);
    s << indent << "calibrated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibrated);
    s << indent << "head_down: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.head_down);
    s << indent << "posture_score: ";
    Printer<float>::stream(s, indent + "  ", v.posture_score);
    s << indent << "head_drop_ratio: ";
    Printer<float>::stream(s, indent + "  ", v.head_drop_ratio);
    s << indent << "baseline_ratio: ";
    Printer<float>::stream(s, indent + "  ", v.baseline_ratio);
    s << indent << "consecutive_droop_frames: ";
    Printer<int32_t>::stream(s, indent + "  ", v.consecutive_droop_frames);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEAD_POSTURE_MODULE_MESSAGE_HEADPOSTURE_H
