#!/usr/bin/env python

"""
user_state_monitor.py
=====================

VISION AND PRESENCE DETECTION MODULE - ROS NODE

This node is the robot-side adapter for the Vision and Presence
Detection Module. It subscribes to the existing face detection
output and publishes a structured UserState message that the rest
of the system (session manager, fatigue monitor) can consume.

INPUTS
    /face_detection/faces  (opencv_apps/FaceArrayStamped)
        From opencv_apps face_detection.launch.
        Same topic and message type used by say_hello_ans.py.

OUTPUTS
    /vision_and_presence_detection  (rchomeedu_vision/UserState)
        Published on every callback so subscribers can see live state.

LAUNCH ORDER (no new packages required, all already on the robot):
    $ roslaunch usb_cam usb_cam-test.launch
    $ roslaunch opencv_apps face_detection.launch image:=/usb_cam/image_raw
    $ roslaunch rchomeedu_vision user_state_monitor.launch

MODULE BOUNDARY
    This node REPORTS what the camera observed. It does not decide
    fatigue. It does not speak. It does not manage sessions. Those
    are other team members' responsibilities (Modules 4, 5, 7).

DEPENDENCIES
    Only packages already installed on the shared robot:
      - rospy
      - opencv_apps (already used by say_hello_ans.py)
      - std_msgs (for time)
    No pip install, no apt install. Shared-robot-safe.
"""

import rospy
import sys
from opencv_apps.msg import FaceArrayStamped

# UserState is generated by catkin from msg/UserState.msg.
# Local IDEs may warn until this file is inside a built catkin package.
from rchomeedu_vision.msg import UserState


class UserStateLogic:
    """Tracks face/eye presence evidence across consecutive callbacks."""

    def __init__(self):
        self.user_present = False
        self.consecutive_eyes_missing = 0
        self.consecutive_face_absent = 0
        self.last_face_seen = None
        self.last_eyes_seen = None
        self.last_update = None

    def reset(self):
        """Reset all internal state. Call when a new session starts."""
        self.user_present = False
        self.consecutive_eyes_missing = 0
        self.consecutive_face_absent = 0
        self.last_face_seen = None
        self.last_eyes_seen = None
        self.last_update = None

    def update(self, faces_exist, eyes_exist, timestamp):
        """
        Update state from one camera callback.

        This class only reports visual evidence. It does not decide fatigue,
        speak, or manage sessions.
        """
        if not faces_exist:
            eyes_exist = False

        if faces_exist and eyes_exist:
            self.user_present = True
            self.consecutive_eyes_missing = 0
            self.consecutive_face_absent = 0
            self.last_face_seen = timestamp
            self.last_eyes_seen = timestamp

        elif faces_exist and not eyes_exist:
            self.user_present = True
            self.consecutive_eyes_missing += 1
            self.consecutive_face_absent = 0
            self.last_face_seen = timestamp

        else:
            self.user_present = False
            self.consecutive_face_absent += 1

        self.last_update = timestamp
        return self.snapshot()

    def snapshot(self):
        return {
            "user_present": self.user_present,
            "consecutive_eyes_missing": self.consecutive_eyes_missing,
            "consecutive_face_absent": self.consecutive_face_absent,
            "last_face_seen": self.last_face_seen,
            "last_eyes_seen": self.last_eyes_seen,
            "timestamp": self.last_update,
        }


class UserStateMonitor:
    def __init__(self):
        rospy.init_node("user_state_monitor")
        rospy.on_shutdown(self.cleanup)

        self.logic = UserStateLogic()

        # Topic names are exposed as ROS params so the integration launch
        # can wire this node without changing this script.
        self.face_topic = rospy.get_param(
            "~face_topic", "/face_detection/faces"
        )
        self.state_topic = rospy.get_param(
            "~state_topic", "/vision_and_presence_detection"
        )

        self.pub = rospy.Publisher(
            self.state_topic, UserState, queue_size=10
        )
        rospy.Subscriber(
            self.face_topic, FaceArrayStamped, self.face_callback
        )

        rospy.loginfo("UserStateMonitor started.")
        rospy.loginfo("  Subscribed to : %s", self.face_topic)
        rospy.loginfo("  Publishing to : %s", self.state_topic)

    def cleanup(self):
        rospy.loginfo("UserStateMonitor shutting down.")

    def _extract_eyes_exist(self, faces):
        """
        Same eyes-detection gate that say_hello_ans.py uses, just
        cleaner. Returns True if ANY detected face has eye data.
        """
        for face_item in faces:
            # opencv_apps FaceArrayStamped: each face has .eyes
            # (a list of Rect). Empty list -> no eyes detected.
            if face_item.eyes:
                return True
        return False

    def face_callback(self, msg):
        now = rospy.Time.now()
        faces = msg.faces

        faces_exist = len(faces) > 0
        eyes_exist = self._extract_eyes_exist(faces) if faces_exist else False

        # Hand off to the shared core logic
        self.logic.update(
            faces_exist=faces_exist,
            eyes_exist=eyes_exist,
            timestamp=now.to_sec(),
        )

        self._publish_state(now)

    def _publish_state(self, stamp):
        out = UserState()
        out.user_present = self.logic.user_present
        out.consecutive_eyes_missing = self.logic.consecutive_eyes_missing
        out.consecutive_face_absent = self.logic.consecutive_face_absent
        out.stamp = stamp
        self.pub.publish(out)

        # loginfo_throttle prevents log spam at camera FPS.
        rospy.loginfo_throttle(
            2.0,
            "user_present=%s  eyes_missing=%d  face_absent=%d" % (
                self.logic.user_present,
                self.logic.consecutive_eyes_missing,
                self.logic.consecutive_face_absent,
            ),
        )


def print_state_callback(msg):
    print("")
    print("stamp                       : %s" % msg.stamp)
    print("user_present                : %s" % msg.user_present)
    print("consecutive_eyes_missing    : %d" % msg.consecutive_eyes_missing)
    print("consecutive_face_absent     : %d" % msg.consecutive_face_absent)


def run_debug_printer():
    rospy.init_node("user_state_debug_printer")
    state_topic = rospy.get_param(
        "~state_topic", "/vision_and_presence_detection"
    )
    rospy.Subscriber(state_topic, UserState, print_state_callback)
    rospy.loginfo("UserState debug printer subscribed to %s", state_topic)
    rospy.spin()


def main():
    args = rospy.myargv(argv=sys.argv)
    if "--print" in args:
        run_debug_printer()
    else:
        UserStateMonitor()
        rospy.spin()


if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        rospy.loginfo("user_state_monitor node terminated.")
