// Generated by gencpp from file vision_presence_module/UserState.msg
// DO NOT EDIT!


#ifndef VISION_PRESENCE_MODULE_MESSAGE_USERSTATE_H
#define VISION_PRESENCE_MODULE_MESSAGE_USERSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_presence_module
{
template <class ContainerAllocator>
struct UserState_
{
  typedef UserState_<ContainerAllocator> Type;

  UserState_()
    : user_present(false)
    , consecutive_eyes_missing(0)
    , consecutive_face_absent(0)
    , stamp()  {
    }
  UserState_(const ContainerAllocator& _alloc)
    : user_present(false)
    , consecutive_eyes_missing(0)
    , consecutive_face_absent(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _user_present_type;
  _user_present_type user_present;

   typedef int32_t _consecutive_eyes_missing_type;
  _consecutive_eyes_missing_type consecutive_eyes_missing;

   typedef int32_t _consecutive_face_absent_type;
  _consecutive_face_absent_type consecutive_face_absent;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::vision_presence_module::UserState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_presence_module::UserState_<ContainerAllocator> const> ConstPtr;

}; // struct UserState_

typedef ::vision_presence_module::UserState_<std::allocator<void> > UserState;

typedef boost::shared_ptr< ::vision_presence_module::UserState > UserStatePtr;
typedef boost::shared_ptr< ::vision_presence_module::UserState const> UserStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_presence_module::UserState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_presence_module::UserState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_presence_module::UserState_<ContainerAllocator1> & lhs, const ::vision_presence_module::UserState_<ContainerAllocator2> & rhs)
{
  return lhs.user_present == rhs.user_present &&
    lhs.consecutive_eyes_missing == rhs.consecutive_eyes_missing &&
    lhs.consecutive_face_absent == rhs.consecutive_face_absent &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_presence_module::UserState_<ContainerAllocator1> & lhs, const ::vision_presence_module::UserState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_presence_module

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision_presence_module::UserState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_presence_module::UserState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_presence_module::UserState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_presence_module::UserState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_presence_module::UserState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_presence_module::UserState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_presence_module::UserState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "073fb340af5920b5f6f7b52a6f27778e";
  }

  static const char* value(const ::vision_presence_module::UserState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x073fb340af5920b5ULL;
  static const uint64_t static_value2 = 0xf6f7b52a6f27778eULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_presence_module::UserState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_presence_module/UserState";
  }

  static const char* value(const ::vision_presence_module::UserState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_presence_module::UserState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool  user_present\n"
"int32 consecutive_eyes_missing\n"
"int32 consecutive_face_absent\n"
"time  stamp\n"
;
  }

  static const char* value(const ::vision_presence_module::UserState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_presence_module::UserState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user_present);
      stream.next(m.consecutive_eyes_missing);
      stream.next(m.consecutive_face_absent);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UserState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_presence_module::UserState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_presence_module::UserState_<ContainerAllocator>& v)
  {
    s << indent << "user_present: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.user_present);
    s << indent << "consecutive_eyes_missing: ";
    Printer<int32_t>::stream(s, indent + "  ", v.consecutive_eyes_missing);
    s << indent << "consecutive_face_absent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.consecutive_face_absent);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_PRESENCE_MODULE_MESSAGE_USERSTATE_H
