<?xml version="1.0"?>
<package format="2">
  <name>vision_presence_module</name>
  <version>0.0.1</version>
  <description>Vision and presence detection module for the focus robot.</description>

  <maintainer email="team13@example.com">Group 13</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>opencv_apps</build_depend>
  <build_depend>message_generation</build_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>opencv_apps</exec_depend>
  <exec_depend>message_runtime</exec_depend>

  <export>
  </export>
</package>
